/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalla.vista;
import javax.swing.*;
/**
 *
 * @author ULISE
 */
public class PantallaCreacion extends javax.swing.JFrame {

    /**
     * Creates new form PantallaCreacion
     */
    public PantallaCreacion() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spnFuerzaH1 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        spnDefensaH1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spnFuerzaV1 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        spnDefensaV1 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        spnVidaV1 = new javax.swing.JSpinner();
        spnVidaH1 = new javax.swing.JSpinner();
        txtNombreH = new javax.swing.JTextField();
        txtNombreV = new javax.swing.JTextField();
        btnCrearH = new javax.swing.JButton();
        btnCrearV = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        spnFuerzaH2 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        spnDefensaH2 = new javax.swing.JSpinner();
        spnDefensaV2 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        spnFuerzaV2 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cboxNombreHeroe = new javax.swing.JComboBox<>();
        cboxNombreVillano = new javax.swing.JComboBox<>();
        spnVidaH2 = new javax.swing.JSpinner();
        spnVidaV2 = new javax.swing.JSpinner();
        btnBorrarH = new javax.swing.JButton();
        btnBorrarV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREACIÓN DE PERSONAJES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(272, 272, 272))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnVolver.setText("Volver");

        btnSiguiente.setText("Siguiente");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("HEROE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("VILLANO");

        jLabel5.setText("VIDA (recomendado 100-200):");

        jLabel9.setText("FUERZA (recomendado 15-30):");

        // Generar valores aleatorios para los spinners
        java.util.Random random = new java.util.Random();
        
        // Vida: 100-160
        int vidaH1 = 100 + random.nextInt(61); // 100 a 160
        int vidaV1 = 100 + random.nextInt(61);
        spnVidaH1.setValue(vidaH1);
        spnVidaV1.setValue(vidaV1);
        
        // Fuerza: 15-25
        int fuerzaH1 = 15 + random.nextInt(11); // 15 a 25
        int fuerzaV1 = 15 + random.nextInt(11);
        spnFuerzaH1.setValue(fuerzaH1);
        spnFuerzaV1.setValue(fuerzaV1);
        
        // Defensa: 8-13
        int defensaH1 = 8 + random.nextInt(6); // 8 a 13
        int defensaV1 = 8 + random.nextInt(6);
        spnDefensaH1.setValue(defensaH1);
        spnDefensaV1.setValue(defensaV1);

        jLabel10.setText("VIDA (recomendado 100-200):");

        jLabel11.setText("DEFENSA (recomendado 5-15):");

        jLabel14.setText("FUERZA (recomendado 15-30):");

        jLabel15.setText("DEFENSA (recomendado 5-15):");

        btnCrearH.setText("Crear Heroe");

        btnCrearV.setText("Crear Villano");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCrearH)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombreH, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5)
                        .addComponent(jLabel9)
                        .addComponent(spnFuerzaH1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addComponent(spnDefensaH1)
                        .addComponent(jLabel11)
                        .addComponent(spnVidaH1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombreV, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel10)
                        .addComponent(jLabel14)
                        .addComponent(spnFuerzaV1)
                        .addComponent(jLabel15)
                        .addComponent(spnDefensaV1)
                        .addComponent(spnVidaV1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                    .addComponent(btnCrearV, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(114, 114, 114))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnVidaV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnVidaH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnFuerzaH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnFuerzaV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnDefensaH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnDefensaV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearH)
                    .addComponent(btnCrearV))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 255));
        jLabel13.setText("HEROE");

        jLabel16.setText("VIDA (recomendado 100-200):");

        jLabel17.setText("FUERZA (recomendado 15-30):");

        spnFuerzaH2.setValue(15);

        jLabel18.setText("DEFENSA (recomendado 5-15):");

        spnDefensaH2.setValue(5);

        spnDefensaV2.setValue(5);

        jLabel19.setText("DEFENSA (recomendado 5-15):");

        spnFuerzaV2.setValue(15);

        jLabel20.setText("FUERZA (recomendado 15-30):");

        jLabel21.setText("VIDA (recomendado 100-200):");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 51));
        jLabel22.setText("VILLANO");

        spnVidaH2.setValue(15);

        spnVidaV2.setValue(15);

        btnBorrarH.setText("Borrar Heroe");
        btnBorrarH.setToolTipText("");

        btnBorrarV.setText("Borrar Villano");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBorrarH)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spnVidaH2)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addComponent(cboxNombreHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spnFuerzaH2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addComponent(spnDefensaH2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addGap(18, 18, 18)
                            .addComponent(cboxNombreVillano, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel21)
                        .addComponent(jLabel20)
                        .addComponent(spnFuerzaV2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addComponent(spnDefensaV2)
                        .addComponent(spnVidaV2))
                    .addComponent(btnBorrarV, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(114, 114, 114))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel22)
                    .addComponent(cboxNombreHeroe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxNombreVillano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnVidaH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnVidaV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnFuerzaH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnFuerzaV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnDefensaH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnDefensaV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarH)
                    .addComponent(btnBorrarV))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cargar", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnSiguiente))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Creacion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Métodos para el controlador
    public JButton getBtnSiguiente() { return btnSiguiente; }
    public JButton getBtnVolver() { return btnVolver; }
    public JButton getBtnCrearH() { return btnCrearH; }
    public JButton getBtnCrearV() { return btnCrearV; }
    public JButton getBtnBorrarH() { return btnBorrarH; }
    public JButton getBtnBorrarV() { return btnBorrarV; }
    
    // Getters para componentes del tab Crear
    public javax.swing.JTextField getTxtNombreH() { return txtNombreH; }
    public javax.swing.JTextField getTxtNombreV() { return txtNombreV; }
    public javax.swing.JSpinner getSpnVidaH1() { return spnVidaH1; }
    public javax.swing.JSpinner getSpnFuerzaH1() { return spnFuerzaH1; }
    public javax.swing.JSpinner getSpnDefensaH1() { return spnDefensaH1; }
    public javax.swing.JSpinner getSpnVidaV1() { return spnVidaV1; }
    public javax.swing.JSpinner getSpnFuerzaV1() { return spnFuerzaV1; }
    public javax.swing.JSpinner getSpnDefensaV1() { return spnDefensaV1; }
    
    // Getters para componentes del tab Cargar
    public javax.swing.JComboBox<String> getCboxNombreHeroe() { return cboxNombreHeroe; }
    public javax.swing.JComboBox<String> getCboxNombreVillano() { return cboxNombreVillano; }
    public javax.swing.JSpinner getSpnVidaH2() { return spnVidaH2; }
    public javax.swing.JSpinner getSpnFuerzaH2() { return spnFuerzaH2; }
    public javax.swing.JSpinner getSpnDefensaH2() { return spnDefensaH2; }
    public javax.swing.JSpinner getSpnVidaV2() { return spnVidaV2; }
    public javax.swing.JSpinner getSpnFuerzaV2() { return spnFuerzaV2; }
    public javax.swing.JSpinner getSpnDefensaV2() { return spnDefensaV2; }
    
    // Métodos de compatibilidad
    public JButton getBtnIniciar() { return btnSiguiente; }
    public JButton getBtnAgregarPersonaje() { return btnSiguiente; }
    public JButton getBtnEliminarPersonaje() { return btnVolver; }
    public JButton getBtnCargar() { return btnVolver; }
    public JButton getBtnSalir() { return btnVolver; }
    
    // Métodos para configuración
    public int getVidaMin() { return 100; }
    public int getVidaMax() { return 160; }
    public void setVidaMin(int min) {}
    public void setVidaMax(int max) {}
    
    public int getFuerzaMin() { return 15; }
    public int getFuerzaMax() { return 25; }
    public void setFuerzaMin(int min) {}
    public void setFuerzaMax(int max) {}
    
    public int getDefensaMin() { return 8; }
    public int getDefensaMax() { return 13; }
    public void setDefensaMin(int min) {}
    public void setDefensaMax(int max) {}
    
    public int getBendicionMin() { return 30; }
    public int getBendicionMax() { return 100; }
    public void setBendicionMin(int min) {}
    public void setBendicionMax(int max) {}
    
    public int getCantidadBatallas() { return 3; }
    public void setCantidadBatallas(int cantidad) {}
    
    public boolean isAtaquesSupremosActivados() { return true; }
    public void setAtaquesSupremosActivados(boolean activado) {}
    
    public void actualizarListaPersonajes(java.util.List<batalla.modelo.Personaje> personajes) {}
    public void limpiarCamposPersonaje() {
        txtNombreH.setText("");
        txtNombreV.setText("");
    }

    // Métodos originales para compatibilidad
    public String getNombreHeroe() { return txtNombreH.getText(); }
    public int getVidaHeroe() { return (int) spnVidaH1.getValue(); }
    public int getFuerzaHeroe() { return (int) spnFuerzaH1.getValue(); }
    public int getDefensaHeroe() { return (int) spnDefensaH1.getValue(); }

    public String getNombreVillano() { return txtNombreV.getText(); }
    public int getVidaVillano() { return (int) spnVidaV1.getValue(); }
    public int getFuerzaVillano() { return (int) spnFuerzaV1.getValue(); }
    public int getDefensaVillano() { return (int) spnDefensaV1.getValue(); }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarH;
    private javax.swing.JButton btnBorrarV;
    private javax.swing.JButton btnCrearH;
    private javax.swing.JButton btnCrearV;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboxNombreHeroe;
    private javax.swing.JComboBox<String> cboxNombreVillano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner spnDefensaH1;
    private javax.swing.JSpinner spnDefensaH2;
    private javax.swing.JSpinner spnDefensaHeroe;
    private javax.swing.JSpinner spnDefensaV1;
    private javax.swing.JSpinner spnDefensaV2;
    private javax.swing.JSpinner spnFuerzaH1;
    private javax.swing.JSpinner spnFuerzaH2;
    private javax.swing.JSpinner spnFuerzaHeroe;
    private javax.swing.JSpinner spnFuerzaV1;
    private javax.swing.JSpinner spnFuerzaV2;
    private javax.swing.JSpinner spnVidaH1;
    private javax.swing.JSpinner spnVidaH2;
    private javax.swing.JSpinner spnVidaHeroe;
    private javax.swing.JSpinner spnVidaV1;
    private javax.swing.JSpinner spnVidaV2;
    private javax.swing.JTextField txtNombreH;
    private javax.swing.JTextField txtNombreHeroe;
    private javax.swing.JTextField txtNombreV;
    // End of variables declaration//GEN-END:variables
}
