/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalla.vista;
/**
 *
 * @author ULISE
 */
public class PantallaBatalla extends javax.swing.JFrame {

    /**
     * Creates new form PantallaBatalla
     */
    public PantallaBatalla() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CombatLog = new javax.swing.JTextArea();
        lblBatalla = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkAtkSupremos = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        spnNumBatallas = new javax.swing.JSpinner();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BATALLA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(266, 266, 266))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblTurno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(102, 153, 255));
        lblTurno.setText("Turno:");

        CombatLog.setEditable(false);
        CombatLog.setColumns(20);
        CombatLog.setRows(5);
        CombatLog.setText("ola");
        CombatLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Combat Log"));
        jScrollPane1.setViewportView(CombatLog);

        lblBatalla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBatalla.setForeground(new java.awt.Color(102, 153, 255));
        lblBatalla.setText("Batalla:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración"));

        chkAtkSupremos.setSelected(true);
        chkAtkSupremos.setText("Ataques Supremos");

        jLabel2.setText("Cantidad Batallas");

        spnNumBatallas.setValue(1);

        btnIniciar.setText("Iniciar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkAtkSupremos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnNumBatallas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(btnIniciar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkAtkSupremos)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIniciar)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnNumBatallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBatalla)
                            .addComponent(lblTurno))
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBatalla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTurno))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTurno(String texto) {
        lblTurno.setText(texto);
    }
    
    public void setInfoPartida(String info) {
        lblBatalla.setText(info);
    }
    
    public javax.swing.JButton getBtnIniciar() { return btnIniciar; }
    public javax.swing.JCheckBox getChkAtkSupremos() { return chkAtkSupremos; }
    public javax.swing.JSpinner getSpnNumBatallas() { return spnNumBatallas; }

    public void agregarLog(String texto) {
        CombatLog.append(texto + "\n");
        // Scroll automático
        CombatLog.setCaretPosition(CombatLog.getDocument().getLength());
    }

    public void limpiarLog() {
        CombatLog.setText("");
    }
    
    public void actualizarEstadoPersonaje(batalla.modelo.Personaje personaje) {
        // Método para actualizar el estado visual del personaje
        // Se puede implementar con paneles o labels específicos
    }
    
    public javax.swing.JButton getBtnPausar() {
        if (btnPausar == null) {
            btnPausar = new javax.swing.JButton("Pausar");
        }
        return btnPausar;
    }
    
    public javax.swing.JButton getBtnGuardar() {
        if (btnGuardar == null) {
            btnGuardar = new javax.swing.JButton("Guardar");
        }
        return btnGuardar;
    }
    
    public javax.swing.JButton getBtnSalir() {
        if (btnSalir == null) {
            btnSalir = new javax.swing.JButton("Salir");
        }
        return btnSalir;
    }
    
    public void setPausado(boolean pausado) {
        if (btnPausar != null) {
            btnPausar.setText(pausado ? "Reanudar" : "Pausar");
        }
    }
    
    private javax.swing.JLabel lblInfoPartida;
    private javax.swing.JButton btnPausar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CombatLog;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JCheckBox chkAtkSupremos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBatalla;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JSpinner spnNumBatallas;
    // End of variables declaration//GEN-END:variables
}
